### PR TITLE
PR opened by mistake

### PR DESCRIPTION
**Pull request by mpentler**
Loads more work to rip out anything other than route stuff. This seems to work for individual flights but /routeset isn't tested yet.

### CODE REVIEW

**Comment by iakat** [comment]
What exactly is happening here...?

**Comment by mpentler** [comment]
What's happening here is I'm a fucking idiot that meant to send this to my own fork but I did it on a phone and have fat fingers. 

Just trying to implement routes without accessing adsb.lol

This can absolutely be deleted - it's for my small scale private aggregator for my amateur radio club and isn't for anything nefarious

**Comment by iakat** [comment]
:+1:

**Comment by iakat** [comment]
You can probably use and / or proxy my API if the usage is low enough.

Might be an easier route.

**Comment by mpentler** [comment]
> You can probably use and / or proxy my API if the usage is low enough.
> 
> Might be an easier route.

I did wonder that but was scared to ask. Maybe it's worth a chat. I feed myself and have brought a few over to .lol and the other sites and mostly this is a private thing for us to learn things.

**Comment by mpentler** [comment]
Weirdly it works fine. I have individual callsigns tested and the container is running on the same server as my aggregator. Just not working in tar1090 yet.

**Comment by iakat** [comment]
Feel free to get in touch via IRC if you want to discuss it more, might be easier. I don't bite. :-)

**Pull request closed without merging**
